### ISSUE TITLE
Dependency updates

### ISSUE THREAD

**Issue by janvonde** [tim-group/jgravatar#3]
Hi,

could you release a new version with updated dependencies? There are some CVEs for the included guava. 

Thank you very much for you work on this lib,

Jan :-)

**Comment by Grundlefleck** [comment]
Bumped all dependencies (to whatever @dependabot said was the most recent) and released to Maven Central, v1.2 now available. Thanks for using and reporting.

**Comment by janvonde** [comment]
Awesome :-D
